export const leagueOfLegends: LeagueOfLegends.IJSON = {
  id: 5426,
  title: 'League of Legends',
  timestamp: null,
  features: [
    'live_client_data',
    'matchState',
    'match_info',
    'death',
    'respawn',
    'abilities',
    'kill',
    'assist',
    'gold',
    'minions',
    'summoner_info',
    'gameMode',
    'teams',
    'level',
    'announcer',
    'counters',
    'damage',
    'heal',
  ],
  data: {
    events: [],
    infos: [],
  },
}
