export const csgo: CSGO.IJSON = {
  id: 7764,
  title: 'Counter-Strike: Global Offensive',
  timestamp: null,
  features: [
    'match_info',
    'kill',
    'death',
    'assist',
    'headshot',
    'round_start',
    'match_start',
    'match_info',
    'match_end',
    'team_round_win',
    'bomb_planted',
    'bomb_change',
    'reloading',
    'fired',
    'weapon_change',
    'weapon_acquired',
    'info',
    'roster',
    'player_activity_change',
    'team_set',
    'replay',
    'counters',
    'mvp',
    'scoreboard',
    'kill_feed',
  ],
  data: {
    events: [],
    infos: [],
  },
}
